### ISSUE TITLE
Comparing with other state-of-the-art algorithms ?

### ISSUE THREAD

**Issue by plutoyuxie** [nuclearboy95/Anomaly-Detection-PatchSVDD-PyTorch#1]
Hi, thanks for opensourcing this excellent project.
Would you compare the classification/segmentation accuracy of PatchSVDD with some recent state-of-the-art algorithms, 
like **Uninformed Students**?

**Comment by nuclearboy95** [comment]
Thanks for you comment. **Uninformed Students** is a great work for anomaly segmentation, but we didn't compare it in the paper because the authors used different metric. Instead, we provided a comparison with the other SOTA methods.

**Comment by plutoyuxie** [comment]
Thanks.
