### ISSUE TITLE
for linux anaconda users, how to solve the problem of not being able to install 'rvai' under linux? waiting for your reply，Thanks!!

### ISSUE THREAD

**Issue by MuchmorePatience** [nuclearboy95/Anomaly-Detection-PatchSVDD-PyTorch#15]

**Comment by nuclearboy95** [comment]
Hi, I don't understand. This project does not have a dependency on 'rvai' package. Thanks!

**Comment by MuchmorePatience** [comment]
Thank u for your reply! I run the code follow the readme ,but it shows as follows:

> Traceback (most recent call last):
  File "main_train.py", line 3, in <module>
    from codes import mvtecad
  File "C:\Users\CCone\Desktop\experiment0506\Patch_SVDD-master\codes\mvtecad.py", line 7, in <module>
    from rvai.types import String, Image
ModuleNotFoundError: No module named 'rvai'
I will appreciate that u can give me some guidances. Thanks!!

**Comment by MuchmorePatience** [comment]
> Hi, I don't understand. This project does not have a dependency on 'rvai' package. Thanks!

Thank u for your reply! I run the code follow the readme ,but it shows as follows:

Traceback (most recent call last):
File "main_train.py", line 3, in
from codes import mvtecad
File "C:\Users\CCone\Desktop\experiment0506\Patch_SVDD-master\codes\mvtecad.py", line 7, in
from rvai.types import String, Image
ModuleNotFoundError: No module named 'rvai'
I will appreciate that u can give me some guidances. Thanks!!

**Comment by MuchmorePatience** [comment]
@nuclearboy95 Thank u for your reply! I run the code follow the readme ,but it shows as follows:

Traceback (most recent call last):
File "main_train.py", line 3, in
from codes import mvtecad
File "C:\Users\CCone\Desktop\experiment0506\Patch_SVDD-master\codes\mvtecad.py", line 7, in
from rvai.types import String, Image
ModuleNotFoundError: No module named 'rvai'

I will appreciate that u can give me some guidances. Thanks!!

**Comment by nuclearboy95** [comment]
Sorry if I was too late.

The line refers to [here](https://github.com/nuclearboy95/Anomaly-Detection-PatchSVDD-PyTorch/blob/934d6238e5e0ad511e2a0e7fc4f4899010e7d892/codes/mvtecad.py#L7), which is an empty line.

I suppose you accidentally pasted a wrong line.

**Comment by MuchmorePatience** [comment]
Thank U for the replying! Thanks！

发自我的
