### ISSUE TITLE
Question on SVDD' loss

### ISSUE THREAD

**Issue by ArdalanM** [nuclearboy95/Anomaly-Detection-PatchSVDD-PyTorch#2]
Hello,

Thank you for your very much for this insightful paper. I have a question regarding the SVDD' loss, equation (4) in your paper.

Lsvdd' ~ || f(p) - f(p') ||

What prevents your network for not returning zeros regardless p or p' (since there are no 'negative samples' in the loss) ?
In your code, the loss tend to converge to zero eventually.

**Comment by nuclearboy95** [comment]
Hi, thanks for your comment.

Lsvdd' converges to zero as long as SGD finds the "global minimum".
Ruff et al. (Deep SVDD) prevented such trivial solution using some tricks (e.g., removing bias).
However, we add self-supervised learning and the resulting loss becomes LpatchSVDD (equation 6).

**Comment by ArdalanM** [comment]
Thanks for the quick respond, it make sense now.

In order to prevent trivial solution (since bias term is learnt in your case) we should/must add the L_ssl term (equation 5).

Many thanks !
