### ISSUE TITLE
occlusion 검출에 대하여..

### ISSUE THREAD

**Issue by isack-ml** [nuclearboy95/Anomaly-Detection-PatchSVDD-PyTorch#23]
안녕하세요. 

훌륭한 논문과 코드 잘 보았습니다. 

해당 논문을 활용하여 순수한 얼굴 이미지와 손으로 가려진 얼굴이미지, 두개의 클래스로 나누어 학습을 진행해보고자 합니다.

드리고 싶은 질문은 두가지 입니다.

1. 이미지 환경이 제한되어있는 기존의 anomaly detection데이터셋과 달리 다양한 얼굴이 입력으로 들어오는 지금의 경우에도 잘 작동할거라고 보시는지?

2.  ValueError: Found input variables with inconsistent numbers of samples: [16121856, 5373952]이러한 에러가 발생하는데 이는 
_ranking.py에서 
y_type = type_of_target(y_true, input_name="y_true")
    if not (y_type == "binary" or (y_type == "multiclass" and pos_label is not None)):
        raise ValueError("{0} format is not supported".format(y_type))
    check_consistent_length(y_true, y_score, sample_weight)
    y_true = column_or_1d(y_true)
    y_score = column_or_1d(y_score)
    assert_all_finite(y_true)
    assert_all_finite(y_score

y_true 와 y_score의 갯수가 달라서 발생하는 듯합니다. 그 이유를 혹시 아실까요?

긴글 읽어주셔서 감사합니다.

**Comment by nuclearboy95** [comment]
안녕하세요

1. 얼굴의 occlusion을 anomaly로 보고 학습을 진행하시겠다는 거지요?
- 우선 이 project에서 타겟한 dataset의 경우, 잘 align된 공장 제품의 이미지입니다.
- 사람 얼굴은 normal과 abnormal 사이의 inter-class variation 뿐 아니라 얼굴들 사이의 intra-class variation도 높을 것으로 생각되는데요, Patch SVDD에서 잘 잡아낼지는 잘 모르겠네요. 직접 돌려보는 수 밖에는 없겠습니다.

2. 16121856은 5373952의 딱 3배네요. 정상 데이터의 3배가 입력으로 들어간 듯 싶은데, RGB 3 channel 이미지의 dimension 순서를 한번 확인해보시면 좋을 것 같습니다.

감사합니다
