### ISSUE TITLE
How to reproduce the reported results?

### ISSUE THREAD

**Issue by YoungGod** [nuclearboy95/Anomaly-Detection-PatchSVDD-PyTorch#4]
Currently, with the default configs, we can't reach the reported results on some MVTec data categories in the paper.  Would you possibly share the trained models or the best training parameters? Thanks.

**Comment by nuclearboy95** [comment]
Hi, I just uploaded the trained models for each class in MVTec AD dataset except the *hazelnut* class.

The model for the *hazelnut* class is missing, and I'm looking for it among a pile of files. I will inform you soon.

Thanks.

**Comment by nuclearboy95** [comment]
I trained the encoder for *hazelnut* class, and uploaded the ckpt showing similar performance as the one reported before.

Thanks.

**Comment by YoungGod** [comment]
Great work. Thanks a lot. ^_^
